add_newline = false

format = """
$username\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$directory\
$character
"""
[character]
success_symbol = "[\\$](green)"
error_symbol = "[\\$](red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
style="blue"


[git_branch]
format = "[\\($branch\\)]($style) "
truncation_length = 20
truncation_symbol = "..."
style="yellow"
