set-option global grepcmd 'rg'

colorscheme gruvbox

add-highlighter global/ number-lines -relative

hook global InsertChar d %{ try %{
  exec -draft hH <a-k>fd<ret> d
  exec <esc>
}}

map global normal '#' ':tmux-terminal-horizontal kak -c %val{session}<ret>'

map global user y '<a-|>wl-copy<ret>'

map global user w ':w<ret>'
map global user q ':q<ret>'
