#!/usr/bin/env bash
set -euo pipefail

repo_full_name=$(gh api repos/:owner/:repo --jq .full_name)
owner=$(dirname "$repo_full_name")
repo=$(basename "$repo_full_name")
pr_number=$(gh pr view --json number --jq .number)

gh api graphql -f query="
{
  repository(owner: \"$owner\", name: \"$repo\") {
    pullRequest(number: $pr_number) {
      reviewThreads(first: 100) {
        nodes {
          id
          isResolved
        }
      }
    }
  }
}" | jq -r '.data.repository.pullRequest.reviewThreads.nodes[] | select(.isResolved == false) | .id' |
	while read -r id; do
		gh api graphql -f query="
    mutation ResolveThread(\$id: ID!) {
      resolveReviewThread(input: {threadId: \$id}) {
        thread { isResolved }
      }
    }" -f id="$id"
	done
