#!/usr/bin/env python
from datetime import datetime
import os
import sys
from time import time
import subprocess
from pathlib import PurePath


def date_string_from_timestamp(ts: float) -> str:
    date = datetime.fromtimestamp(ts)
    [year, month, day, hour, minute,] = map(
        lambda n: f"0{s}" if len((s := str(n))) < 2 else s,
        [
            date.year - 2000,
            date.month,
            date.day,
            date.hour,
            date.minute,
        ],
    )
    return f"{year}-{month}-{day}-{hour}{minute}"


if __name__ == "__main__":
    notes_path = PurePath(os.environ["HOME"], "notes")
    editor = os.environ["EDITOR"]

    os.chdir(notes_path)
    file_name = (
        f"{date_string_from_timestamp(time())}-{args[1]}.md"
        if len(args := sys.argv) > 1
        else (
            subprocess.run(["fzf", "--layout=reverse"], stdout=subprocess.PIPE)
            .stdout.decode("utf-8", "strict")
            .replace("\n", "")
        )
    )
    if not file_name:
        sys.exit()
    subprocess.run([editor, PurePath(notes_path, file_name)])
